// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	Name     string      `json:"name"`
	Category string      `json:"category"`
	ID       pgtype.UUID `json:"id"`
}

type Game struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type LoadAttachment struct {
	LoadoutID    pgtype.UUID `json:"loadoutId"`
	AttachmentID pgtype.UUID `json:"attachmentId"`
}

type Loadout struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	Title          string             `json:"title"`
	Source         pgtype.Text        `json:"source"`
	SourceUrl      pgtype.Text        `json:"sourceUrl"`
	WeaponName     string             `json:"weaponName"`
	WeaponCategory string             `json:"weaponCategory"`
	CreatedBy      pgtype.UUID        `json:"createdBy"`
	GameID         pgtype.UUID        `json:"gameId"`
	Attachments    []pgtype.UUID      `json:"attachments"`
}
